name: CI

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    shell: pwsh

jobs:
  build-and-release:
    name: Build & Release

    runs-on: [self-hosted, windows, server]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Show Environment
        run: |
          $PSVersionTable
          $pwd
          Write-Host Path:
          $env:PATH
          Write-Host
          Write-Host whoami:
          whoami
          Write-Host
          Write-Host Default Environment Variables:
          Write-Host "CI: $env:CI"
          Write-Host "GITHUB_ACTION: $env:GITHUB_ACTION"
          Write-Host "GITHUB_ACTION_PATH: $env:GITHUB_ACTION_PATH"
          Write-Host "GITHUB_ACTION_REPOSITORY: $env:GITHUB_ACTION_REPOSITORY"
          Write-Host "GITHUB_ACTIONS: $env:GITHUB_ACTIONS"
          Write-Host "GITHUB_ACTOR: $env:GITHUB_ACTOR"
          Write-Host "GITHUB_ACTOR_ID: $env:GITHUB_ACTOR_ID"
          Write-Host "GITHUB_API_URL: $env:GITHUB_API_URL"
          Write-Host "GITHUB_BASE_REF: $env:GITHUB_BASE_REF"
          Write-Host "GITHUB_ENV: $env:GITHUB_ENV"
          Write-Host "GITHUB_EVENT_NAME: $env:GITHUB_EVENT_NAME"
          Write-Host "GITHUB_EVENT_PATH: $env:GITHUB_EVENT_PATH"
          Write-Host "GITHUB_GRAPHQL_URL: $env:GITHUB_GRAPHQL_URL"
          Write-Host "GITHUB_HEAD_REF: $env:GITHUB_HEAD_REF"
          Write-Host "GITHUB_JOB: $env:GITHUB_JOB"
          Write-Host "GITHUB_PATH: $env:GITHUB_PATH"
          Write-Host "GITHUB_REF: $env:GITHUB_REF"
          Write-Host "GITHUB_REF_NAME: $env:GITHUB_REF_NAME"
          Write-Host "GITHUB_REF_PROTECTED: $env:GITHUB_REF_PROTECTED"
          Write-Host "GITHUB_REF_TYPE: $env:GITHUB_REF_TYPE"
          Write-Host "GITHUB_REPOSITORY: $env:GITHUB_REPOSITORY"
          Write-Host "GITHUB_REPOSITORY_ID: $env:GITHUB_REPOSITORY_ID"
          Write-Host "GITHUB_REPOSITORY_OWNER: $env:GITHUB_REPOSITORY_OWNER"
          Write-Host "GITHUB_REPOSITORY_OWNER_ID: $env:GITHUB_REPOSITORY_OWNER_ID"
          Write-Host "GITHUB_RETENTION_DAYS: $env:GITHUB_RETENTION_DAYS"
          Write-Host "GITHUB_RUN_ATTEMPT: $env:GITHUB_RUN_ATTEMPT"
          Write-Host "GITHUB_RUN_ID: $env:GITHUB_RUN_ID"
          Write-Host "GITHUB_RUN_NUMBER: $env:GITHUB_RUN_NUMBER"
          Write-Host "GITHUB_SERVER_URL: $env:GITHUB_SERVER_URL"
          Write-Host "GITHUB_SHA: $env:GITHUB_SHA"
          Write-Host "GITHUB_STEP_SUMMARY: $env:GITHUB_STEP_SUMMARY"
          Write-Host "GITHUB_WORKFLOW: $env:GITHUB_WORKFLOW"
          Write-Host "GITHUB_WORKFLOW_REF: $env:GITHUB_WORKFLOW_REF"
          Write-Host "GITHUB_WORKFLOW_SHA: $env:GITHUB_WORKFLOW_SHA"
          Write-Host "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          Write-Host "RUNNER_ARCH: $env:RUNNER_ARCH"
          Write-Host "RUNNER_DEBUG: $env:RUNNER_DEBUG"
          Write-Host "RUNNER_NAME: $env:RUNNER_NAME"
          Write-Host "RUNNER_OS: $env:RUNNER_OS"
          Write-Host "RUNNER_TEMP: $env:RUNNER_TEMP"
          Write-Host "RUNNER_TOOL_CACHE: $env:RUNNER_TOOL_CACHE"

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Update Global Node.js
        run: |
          fnm install ${{ steps.setup-node.outputs.node-version }}
          fnm use ${{ steps.setup-node.outputs.node-version }}

      - name: Install
        run: |
          pnpm install --frozen-lockfile

      - name: Build
        run: ./build.ps1

      - name: Archive
        run: ./archive.ps1

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          preserve_order: true
          files: |
            ./src/java/*.jar
            ./src/module/*.tko
            ./dist/*.zip
            ./dist/*.sha256

      - name: Wait before Dispatch
        if: startsWith(github.ref, 'refs/tags/')
        run: Start-Sleep -Seconds 30

      - name: Dispatch Scoop Excavator
        if: startsWith(github.ref, 'refs/tags/')
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SCOOP_NORGATEAV_AMX }}
          repository: norgate-av/scoop-norgateav-amx
          event-type: excavate
          client-payload: |-
            {
              "repo": {
                "name": "${{ github.repository }}",
                "owner": "${{ github.repository_owner }}",
                "ref": "${{ github.ref }}"
              }
            }
